export const prizeManager_ABI = [
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "BalanceWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "participant",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "competitionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "ParticipantPrizeClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "competitionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "winnerPrize",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "participantPrizePerTicket",
        type: "uint256",
      },
    ],
    name: "PrizeCalculated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "competitionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PrizeClaimed",
    type: "event",
  },
  {
    inputs: [],
    name: "GRACE_PERIOD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PARTICIPANT_PERCENT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WINNER_PERCENT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "addToClaimableBalance",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "collectionAddress",
            type: "address",
          },
          { internalType: "uint8[]", name: "rarityTiers", type: "uint8[]" },
          { internalType: "uint256", name: "ticketPrice", type: "uint256" },
          { internalType: "address", name: "treasuryWallet", type: "address" },
          { internalType: "uint256", name: "treasuryPercent", type: "uint256" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bool", name: "boosterBoxEnabled", type: "bool" },
          {
            internalType: "address",
            name: "boosterBoxAddress",
            type: "address",
          },
          { internalType: "address", name: "verifierAddress", type: "address" },
          {
            internalType: "enum ICompetitionStorage.CompetitionState",
            name: "state",
            type: "uint8",
          },
          { internalType: "address", name: "winner", type: "address" },
          { internalType: "uint256", name: "prizePool", type: "uint256" },
          { internalType: "uint256", name: "totalTickets", type: "uint256" },
          { internalType: "bool", name: "winnerDeclared", type: "bool" },
          {
            internalType: "uint256",
            name: "winnerDeclaredAt",
            type: "uint256",
          },
          { internalType: "bool", name: "emergencyPaused", type: "bool" },
        ],
        internalType: "struct ICompetitionStorage.Competition",
        name: "comp",
        type: "tuple",
      },
    ],
    name: "calculatePotentialPrizes",
    outputs: [
      { internalType: "uint256", name: "winnerPrize", type: "uint256" },
      { internalType: "uint256", name: "prizePerTicket", type: "uint256" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "competitionId", type: "uint256" },
      {
        components: [
          {
            internalType: "address",
            name: "collectionAddress",
            type: "address",
          },
          { internalType: "uint8[]", name: "rarityTiers", type: "uint8[]" },
          { internalType: "uint256", name: "ticketPrice", type: "uint256" },
          { internalType: "address", name: "treasuryWallet", type: "address" },
          { internalType: "uint256", name: "treasuryPercent", type: "uint256" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bool", name: "boosterBoxEnabled", type: "bool" },
          {
            internalType: "address",
            name: "boosterBoxAddress",
            type: "address",
          },
          { internalType: "address", name: "verifierAddress", type: "address" },
          {
            internalType: "enum ICompetitionStorage.CompetitionState",
            name: "state",
            type: "uint8",
          },
          { internalType: "address", name: "winner", type: "address" },
          { internalType: "uint256", name: "prizePool", type: "uint256" },
          { internalType: "uint256", name: "totalTickets", type: "uint256" },
          { internalType: "bool", name: "winnerDeclared", type: "bool" },
          {
            internalType: "uint256",
            name: "winnerDeclaredAt",
            type: "uint256",
          },
          { internalType: "bool", name: "emergencyPaused", type: "bool" },
        ],
        internalType: "struct ICompetitionStorage.Competition",
        name: "comp",
        type: "tuple",
      },
    ],
    name: "calculatePrizes",
    outputs: [
      { internalType: "uint256", name: "winnerPrize", type: "uint256" },
      { internalType: "uint256", name: "prizePerTicket", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "competitionId", type: "uint256" },
      { internalType: "address", name: "participant", type: "address" },
      {
        components: [
          {
            internalType: "address",
            name: "collectionAddress",
            type: "address",
          },
          { internalType: "uint8[]", name: "rarityTiers", type: "uint8[]" },
          { internalType: "uint256", name: "ticketPrice", type: "uint256" },
          { internalType: "address", name: "treasuryWallet", type: "address" },
          { internalType: "uint256", name: "treasuryPercent", type: "uint256" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bool", name: "boosterBoxEnabled", type: "bool" },
          {
            internalType: "address",
            name: "boosterBoxAddress",
            type: "address",
          },
          { internalType: "address", name: "verifierAddress", type: "address" },
          {
            internalType: "enum ICompetitionStorage.CompetitionState",
            name: "state",
            type: "uint8",
          },
          { internalType: "address", name: "winner", type: "address" },
          { internalType: "uint256", name: "prizePool", type: "uint256" },
          { internalType: "uint256", name: "totalTickets", type: "uint256" },
          { internalType: "bool", name: "winnerDeclared", type: "bool" },
          {
            internalType: "uint256",
            name: "winnerDeclaredAt",
            type: "uint256",
          },
          { internalType: "bool", name: "emergencyPaused", type: "bool" },
        ],
        internalType: "struct ICompetitionStorage.Competition",
        name: "comp",
        type: "tuple",
      },
      { internalType: "bool", name: "hasTicket", type: "bool" },
    ],
    name: "claimParticipantPrize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "competitionId", type: "uint256" },
      { internalType: "address", name: "winner", type: "address" },
      {
        components: [
          {
            internalType: "address",
            name: "collectionAddress",
            type: "address",
          },
          { internalType: "uint8[]", name: "rarityTiers", type: "uint8[]" },
          { internalType: "uint256", name: "ticketPrice", type: "uint256" },
          { internalType: "address", name: "treasuryWallet", type: "address" },
          { internalType: "uint256", name: "treasuryPercent", type: "uint256" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bool", name: "boosterBoxEnabled", type: "bool" },
          {
            internalType: "address",
            name: "boosterBoxAddress",
            type: "address",
          },
          { internalType: "address", name: "verifierAddress", type: "address" },
          {
            internalType: "enum ICompetitionStorage.CompetitionState",
            name: "state",
            type: "uint8",
          },
          { internalType: "address", name: "winner", type: "address" },
          { internalType: "uint256", name: "prizePool", type: "uint256" },
          { internalType: "uint256", name: "totalTickets", type: "uint256" },
          { internalType: "bool", name: "winnerDeclared", type: "bool" },
          {
            internalType: "uint256",
            name: "winnerDeclaredAt",
            type: "uint256",
          },
          { internalType: "bool", name: "emergencyPaused", type: "bool" },
        ],
        internalType: "struct ICompetitionStorage.Competition",
        name: "comp",
        type: "tuple",
      },
    ],
    name: "claimWinnerPrize",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "claimableBalances",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getClaimableBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "competitionId", type: "uint256" },
    ],
    name: "getParticipantPrizePerTicket",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "competitionId", type: "uint256" },
    ],
    name: "isPrizeCalculated",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "withdrawBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
